# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: csv command
Download, resample and convert CSV files into pandas:
{{{
csv url PAIRSYMBOL       - show a URL where you can download  1 minute Mt HST data
csv resample SRAW1MINFILE, SRESAMPLEDCSV, STIMEFRAME - Resample 1 minute CSV data,
                                                       to a new timeframe
                                                       and save it as CSV file
}}}
For help on subcommands type: csv help <sub> 



    Scenario: csv url
For help on options type: help csv

        Given We get help when we type "csv help url"
        """csv url PAIRSYMBOL       
                - show a URL where you can download  1 minute Mt HST data
                
        For help on options type: help csv
        """


    Scenario: csv resample
For help on options type: help csv

        Given We get help when we type "csv help resample"
        """csv resample SRAW1MINFILE, SRESAMPLEDCSV, STIMEFRAME 
                - Resample 1 minute CSV data, to a new timeframe and save it as CSV file
                
        For help on options type: help csv
        """
