# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: chart command
chart
For help on subcommands type: chart help <sub> 



    Scenario: chart list
For help on options type: help chart

        Given We get help when we type "chart help list"
        """chart list
                
        For help on options type: help chart
        """


    Scenario: chart get
For help on options type: help chart

        Given We get help when we type "chart help get"
        """chart get
                
        For help on options type: help chart
        """


    Scenario: chart set
For help on options type: help chart

        Given We get help when we type "chart help set"
        """chart list
                
        For help on options type: help chart
        """
