# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: subscribe command

Subscribe to messages from RabbitMQ on a given topic:
{{{
  sub get               - get the current target for subscribe; defaults to:
                        the first value of default['lOnlineTargets'] in OTCmd2.ini
  sub set TARGET        - set the target for subscribe, must be one of:
                        the values of default['lOnlineTargets'] in OTCmd2.ini
  sub config            - configure the current target for subscribe: [KEY [VAL]]
  sub run TOPIC1 ...    - start a thread to listen for messages,
                          TOPIC is one or more Rabbit topic patterns.
  sub topics            - shows topics subscribed to.
  sub hide TOPIC        - stop seeing TOPIC messages (e.g. tick - not a pattern)
  sub show              - list the message topics that are being hidden
  sub show TOPIC        - start seeing TOPIC messages (e.g. tick - not a pattern)
  sub pprint ?0|1       - seeing TOPIC messages with pretty-printing,
                          with 0 - off, 1 - on, no argument - current value
  sub thread info       - info on the thread listening for messages.
  sub thread stop       - stop a thread listening for messages.
  sub thread enumerate  - enumerate all threads
}}}

Common RabbitMQ topic patterns are:
* {{{#}}} for all messages,
* {{{tick.#}}} for ticks,
* {{{timer.#}}} for timer events,
* {{{retval.#}}} for return values.

You can choose as specific chart with syntax like:
{{{
    tick.oChart.EURGBP.240.93ACD6A2.#
}}}
The RabbitMQ host and login information is set in the {{{[RabbitMQ]}}}
section of the {{{OTCmd2.ini}}} file; see the {{{-c/--config}}} command-line options.
For help on subcommands type: subscribe help <sub> 



    Scenario: subscribe get
For help on options type: help subscribe

        Given We get help when we type "subscribe help get"
        """subscribe get
                
        For help on options type: help subscribe
        """


    Scenario: subscribe config
For help on options type: help subscribe

        Given We get help when we type "subscribe help config"
        """subscribe config - configure the current target for subscribe:  [KEY [VAL]]
                
        For help on options type: help subscribe
        """


    Scenario: subscribe topics
For help on options type: help subscribe

        Given We get help when we type "subscribe help topics"
        """subscribe topics: shows topics subscribed to
                
        For help on options type: help subscribe
        """


    Scenario: subscribe set
For help on options type: help subscribe

        Given We get help when we type "subscribe help set"
        """subscribe set
                
        For help on options type: help subscribe
        """


    Scenario: subscribe thread
For help on options type: help subscribe

        Given We get help when we type "subscribe help thread"
        """thread info       - info on the thread listening for messages.
        thread stop       - stop a thread listening for messages.
        For help on options type: help subscribe
        """


    Scenario: subscribe hide
For help on options type: help subscribe

        Given We get help when we type "subscribe help hide"
        """subscribe hide: stop seeing TOPIC messages (e.g. tick - not a pattern)
                
        For help on options type: help subscribe
        """


    Scenario: subscribe show
For help on options type: help subscribe

        Given We get help when we type "subscribe help show"
        """subscribe show
        start seeing TOPIC messages (e.g. tick - not a pattern)
                
        For help on options type: help subscribe
        """


    Scenario: subscribe pprint
For help on options type: help subscribe

        Given We get help when we type "subscribe help pprint"
        """subscribe pprint:
        - seeing TOPIC messages with pretty-printing,
        - with 0 - off, 1 - on, no argument - current value
        For help on options type: help subscribe
        """


    Scenario: subscribe run
For help on options type: help subscribe

        Given We get help when we type "subscribe help run"
        """subscribe run: start a thread to listen for messages,
                
        For help on options type: help subscribe
        """


    Scenario: subscribe list
For help on options type: help subscribe

        Given We get help when we type "subscribe help list"
        """subscribe list
                
        For help on options type: help subscribe
        """
