# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: publish command

Publish a message via RabbitMQ to a given chart on a OTMql4Py enabled terminal:
{{{
}}}
You wont see the return value unless you have already done a:
{{{
  sub run retval.#
}}}
The RabbitMQ host and login information is set in the {{{[RabbitMQ]}}}
section of the {{{OTCmd2.ini}}} file; see the {{{-c/--config}}} command-line options.
For help on subcommands type: publish help <sub> 



    Scenario: publish get
For help on options type: help publish

        Given We get help when we type "publish help get"
        """pub get                   - get the current target for publish; defaults to:
                                    the first value of default['lOnlineTargets'] in OTCmd2.ini
                
        For help on options type: help publish
        """


    Scenario: publish config
For help on options type: help publish

        Given We get help when we type "publish help config"
        """pub config                - configure the current target for publish: [KEY [VAL]]
                
        For help on options type: help publish
        """


    Scenario: publish set
For help on options type: help publish

        Given We get help when we type "publish help set"
        """  pub set TARGET            - set the target for publish,
                
        For help on options type: help publish
        """


    Scenario: publish wait
For help on options type: help publish

        Given We get help when we type "publish help wait"
        """pub wait COMMAND ARG1 ... - publish a Mql command to Mt4 and wait for the result,
              the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish exec
For help on options type: help publish

        Given We get help when we type "publish help exec"
        """pub wait COMMAND ARG1 ... - publish a Mql command to Mt4 and wait for the result,
              the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish sync
For help on options type: help publish

        Given We get help when we type "publish help sync"
        """pub wait COMMAND ARG1 ... - publish a Mql command to Mt4 and wait for the result,
              the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish cmd
For help on options type: help publish

        Given We get help when we type "publish help cmd"
        """pub wait COMMAND ARG1 ... - publish a Mql command to Mt4 asyncronsly,
              the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish async
For help on options type: help publish

        Given We get help when we type "publish help async"
        """pub wait COMMAND ARG1 ... - publish a Mql command to Mt4 asyncronsly,
              the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish eval
For help on options type: help publish

        Given We get help when we type "publish help eval"
        """pub eval COMMAND ARG1 ... - publish a Python command to the OTMql4Py,
        the command should be a single string, with a space seperating arguments.
                
        For help on options type: help publish
        """


    Scenario: publish json
For help on options type: help publish

        Given We get help when we type "publish help json"
        """
                
        For help on options type: help publish
        """
