# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: backtest command

Backtest recipes with chefs, and serve the results as metrics and plots.

The subcommands are:
* omlette   - An omlette is an HDF5 file that saves all the data from a backtest
* feed      - Create feeds (pandas DataFrames) from CSV OHLCV files
* recipe    - Set the recipe that the chef will use, and make the ingredients from the feeds
* chef      - Set the chef that we will use, and cook from the ingredients and the feeds
* servings  - List the servings the chef has cooked, and dish out the servings
* plot      - Plot the servings the chef has cooked, using matplotlib
For help on subcommands type: backtest help <sub> 



    Scenario: backtest omlette
For help on options type: help backtest

        Given We get help when we type "backtest help omlette"
        """backtest omlette
        An omlette is an HDF5 file that saves all the information from a backtest,
        including the metadata: all of parameter values that were used in the recipe,
        the parameters used by the cook, and the servings results.
        You should open an omlette before you backtest giving it a filename,
        and close it after the 'chef cook' and 'servings'.
        {{{
        back omlette open FILE           - open an HDF file to save all the backtest parts
        back omlette check               - show the current omlette filename
        back omlette display             - display the current omlette HDF sections
        back omlette close               - close the HDF file saving the omlette
        }}}
        Real Soon Now you will be able to enjoy them more by reloading previously saved
        omlettes, plotting the data or the results, and adding or editing comments.
                
        For help on options type: help backtest
        """
