# -*-mode: feature; encoding: utf-8-dos -*-
# This file is automatically generated - edits will be lost

Feature: make command
The make command lets us make things that are useful, such as making
the feature files that will be used to run the tests. 

* make [--features_dir] features: will generate the test feature files to test the code.
For help on subcommands type: make help <sub> 



    Scenario: make features
For help on options type: help make

        Given We get help when we type "make help features"
        """make [--features_dir] features will generate the test feature files
        that are used to test the code from the code itself. This way, the
        documentation in the feature files is drawn directly from the documentation
        in the code, which makes it easier to keep it up-to-date with the code.
        make features uses the --features_dir dir option to the make command to know what
        directory the feature files will be written to. The directory must exist.
        For help on options type: help make
        """
