# -*-mode: python; py-indent-offset: 4; encoding: utf-8-dos; coding: utf-8 -*-

"""The make templates are just using format, but could use mako or genshi
"""

SFEATURE_HEAD = "# -*-mode: feature; encoding: utf-8-dos -*-"
SFEATURE_HEAD += "\n# This file is automatically generated - edits will be lost"

SFEATURE_TEMPLATE = SFEATURE_HEAD + """

Feature: %(sname)s command
%(shelp)s

"""

SSCENARIO_TEMPLATE = """

    Scenario: %(sname)s
%(shelp)s
"""

SGIVEN_STEP_TEMPLATE = """        Given %(scommand)s
%(sstring)s
"""
